#cloud-config

# Using https://github.com/TrueOsiris/docker-vrising since it appears to still be maintained. We might need to fork if its no longer maintained.

users:
- name: cloudservice
  uid: 2000

write_files:
- path: /etc/systemd/system/cloudservice.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=Start a simple docker container

    [Service]
    ExecStart=/usr/bin/docker run --rm -p 9876:9876/udp -p 9877:9877/udp -u 2000 -v /mnt/disks/games/vrising:/saves --name=mycloudservice rueOsiris/docker-vrising
    ExecStop=/usr/bin/docker stop mycloudservice
    ExecStopPost=/usr/bin/docker rm mycloudservice

runcmd:
- systemctl daemon-reload
- systemctl start cloudservice.service

# Optional once-per-boot setup. For example: mounting a PD.
bootcmd:
- fsck.ext4 -tvy /dev/sdb
- mkdir -p /mnt/disks/games
- mount -t ext4 -O ... /dev/sdb /mnt/disks/games